FROM python:3.12-slim

# Arbeitsverzeichnis im Container
WORKDIR /app

# Abhängigkeiten kopieren und installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Applikationscode kopieren
COPY src ./src
COPY .env .env
copy params.yaml params.yaml
# Port (nur Dokumentation, optional)
EXPOSE 8000

# Startbefehl
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]