{
 "title": "Mlops Weather Dashboard Copy",
 "time": { "from": "2026-01-20T21:59:06.205Z", "to": "2026-01-20T21:59:59.233Z" },
 "panels": [
  {
   "title": "Weather Api Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"weather-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average respond times ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (endpoint) (api_request_duration_seconds_sum / api_request_duration_seconds_count)",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  {
   "title": "Total api Requests by endpoint",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (api_requests_total) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Model Metrics",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_split_id", "legendFormat": "Split ID" },
    { "expr": "model_accuracy", "legendFormat": "Accuracy" },
    { "expr": "model_f1_score", "legendFormat": "F1 Score" },
    { "expr": "model_precision     ", "legendFormat": "Precision" },
    { "expr": "model_recall", "legendFormat": "Recall" },
    { "expr": "model_roc_auc", "legendFormat": "ROC-AUC" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[5m])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\r\n    /\r\n    node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}