{
 "title": "MLOps Project: Weather Prediction Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Weather Api Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"weather-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (endpoint) (api_request_duration_seconds_sum / api_request_duration_seconds_count)",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "API Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(api_requests_total[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total API Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "api_requests_total{}", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Model Metrics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_split_id", "legendFormat": "Split ID" },
    { "expr": "model_f1_score", "legendFormat": "F1 Score" },
    { "expr": "model_accuracy", "legendFormat": "Accuracy" },
    { "expr": "model_precision     ", "legendFormat": "Precision" },
    { "expr": "model_recall", "legendFormat": "Recall" },
    { "expr": "model_roc_auc", "legendFormat": "ROC-AUC" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\r\n    /\r\n    node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[5m])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  }
 ]
}